### ISSUE TITLE
the url of common.go in README is not exist

### ISSUE THREAD

**Issue by gao-feng** [aporeto-inc/trireme-example#2]
https://github.com/aporeto-inc/trireme-example/blob/master/README.md#understanding-the-simple-example

```
# Understanding the simple example.

Let's dive into the code. This simple example is almost fully defined in [common.go](common/common.go).
```

**Comment by dstiliadis** [comment]
Fixed with https://github.com/aporeto-inc/trireme-example/commit/3fd55459a2a1a1ec4a0c1de743c203b253d63804
